### ISSUE TITLE
All page screenshot doesn't work

### ISSUE THREAD

**Issue by zal-ua** [Aminadav/screenshot-extension#100]
All page screenshot makes screenshot of visible part of a page.

**Comment by Fight4freeTech** [comment]
Similar Google Chrome updated and wouldn't work unless I clicked allow something... Now there are some pages that I cant get to give a full screenshot mostly news webpages but also a biblical studies page... Pages ( all of the http://biblehub.com and all of the www.i24news.tv/en pages don't work. but also a couple of the other news print pages also wont fully print screen )

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
