### ISSUE TITLE
Print preview produces blank page

### ISSUE THREAD

**Issue by magoo99** [Aminadav/screenshot-extension#101]
Hi, 
I try to use the Open Screenshot extension on Chrome for Mac (61.0.3163.91).
The extension collects the website content correctly, but when I attempt to print it, it only produces blank pages. However, header and footer sections are populated correctly.
Same problem when trying to save as pdf.
MacOS version is 10.11.6 (El Capitan).

Thanks for any suggestion on how to print or save to pdf.

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
