### ISSUE TITLE
A all page screenshot error occurs

### ISSUE THREAD

**Issue by thanhnguyentung95** [Aminadav/screenshot-extension#103]
It doesn't take all page, some parts of the page I took was gray.

**Comment by Fight4freeTech** [comment]
Similar Google Chrome updated and wouldn't work unless I clicked allow something... Now there are some pages that I cant get to give a full screenshot mostly news webpages but also a biblical studies page

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
