### ISSUE TITLE
All Page Screen Shot Fail

### ISSUE THREAD

**Issue by tcmbsears** [Aminadav/screenshot-extension#107]
I love your product, but it isn't working right.  

All Page Screen Shot stops before it captures the entire page.  

![image](https://user-images.githubusercontent.com/28990373/31094997-2023f146-a785-11e7-9320-e9b45e70658b.png)

**Comment by essteffan** [comment]
Same problem here. I use macos Sierra.

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
