### ISSUE TITLE
no full page capture

### ISSUE THREAD

**Issue by Wellan1575** [Aminadav/screenshot-extension#110]
[Disjoncteur phase + neutre à vis 20 A - DEBFLEX - Brico Dépôt.pdf](https://github.com/Aminadav/screenshot-extension/files/1366824/Disjoncteur.phase.neutre.a.vis.20.A.-.DEBFLEX.-.Brico.Depot.pdf)
Hi,
I've been using Open Screenshot for many years (XP, Vista, Win7, Win 10) Without ever having a problem. But for some time, with Win 8.1, I no longer do full page capture. 
exemple > attach file
page link : http://www.bricodepot.fr/st-germain-du-puy/disjoncteur-phase-neutre-a-vis-20-a/prod29353/#
[Disjoncteur phase + neutre à vis 20 A - DEBFLEX - Brico Dépôt.pdf](https://github.com/Aminadav/screenshot-extension/files/1366823/Disjoncteur.phase.neutre.a.vis.20.A.-.DEBFLEX.-.Brico.Depot.pdf)

Thank for your help
Richard

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
