### ISSUE TITLE
All page screen shot getting cut off

### ISSUE THREAD

**Issue by reardon-c** [Aminadav/screenshot-extension#112]
Hi,
I've been using the all page screenshots functionality successfully for a couple months but it has stopped working. It now consistently cuts off the bottom of all my screenshots.
Thanks

**Comment by nvthaovn** [comment]
I also encounter this error, today

**Comment by redcenter** [comment]
Exactly the same problem, worked fine before.

Chrome Version 61.0.3163.100 (Official Build) (64-bit) - Ubuntu 16.04.3 LTS

**Comment by fairlothlorien** [comment]
Same here, although I am a recent user so it has never worked for me. In the Editor screen it displays a screenshot the full length of the page but only the visible parts of the page are actually there, the rest is just grey and white checkerboard. When saved it is just a PNG of the visible part of the page, not the full scrolling screenshot.

Also, to illustrate the issue I created the attached screenshots. In doing so I discovered that the Visible Screenshot also doesn't work. It cropped the visible region of the page to about a 3rd of what was actually there.

Also, the Capture Region option just put a blue overlay over the page but I couldn't get it to do anything. It wouldn't allow me to select a region and if I just clicked on it the overlay went away, no screenshot at all.

See screenshots attached.

Using the All page option with this extension:
![demo of screenshot - google search - all page](https://user-images.githubusercontent.com/32829745/31918360-8dcaa0ca-b89f-11e7-9c9b-3a7cea9bd79b.png)

Using a different extension to screenshot the same whole page:
![actual - all page](https://user-images.githubusercontent.com/32829745/31918497-57ec4962-b8a0-11e7-94e2-de4a81eee6e1.png)

Using the All page option with this extension:
![demo of screenshot - google search - visible region](https://user-images.githubusercontent.com/32829745/31918361-8e0863ec-b89f-11e7-837c-59c7d45fcf8d.png)

Using a different extension to screenshot the same actual visible region:
![actual - visible region](https://user-images.githubusercontent.com/32829745/31918359-8d903e62-b89f-11e7-9135-41831c49086d.png)

**Comment by k4rz4** [comment]
I have fixed this. 
For some reason when calling action full page screenshot doesen't scroll, but in same time it doesen't push to array 'screenshot.screens'. 

- Add  2 params
screenshoot.heightUl:0,
screenshot.scrollStep: 0

``` js
ans: function (mess) {
    if (api.stop) {
      return ;
    }
    if (!mess && chrome.runtime.lastError) {
      if (screenshot.retries > 1 && screenshot.scroll) {
        api.callPopup({type: 'message', message: 'Sorry, we can not take a full screenshot of this webpage. This might be because it is not fully loaded. Please report this issue.'});
        return ;
      } else if (screenshot.retries > 1) {
        mess = {left:0,top:0,finish:true};
      } else {
        codeinjector.executeOnTab(
          screenshot.thisTabId,
          screenshot.thisTab,
          true,
          screenshot.addScreen
        );
        return ;
      }
    }
    if(mess.top==null) {mess.top=0;mess.left=0}
    if (mess && mess.description) {
      screenshot.description = mess.description
    }
    var upCrop = 0, leftCrop = 0;
    if (screenshot.cropData) {
      upCrop = screenshot.cropData.x1
      upCrop = screenshot.cropData.x1
    }
    var cb = function (data) {
      chrome.tabs.executeScript(screenshot.thisTabId, {code:'var result; result = window.innerHeight; result'},function(result) {
        screenshot.heightUl = result[0];
      });
      mess.top = screenshot.heightUl;
      if (chrome.runtime.lastError) {
        console.error(chrome.runtime.lastError);
      }
      if (api.stop) return ;
      if (parseInt(mess.top) === 0 ){
        mess.top++;
        screenshot.screens.push({left: parseInt(mess.left), top: parseInt(mess.top), data: data});
      }
      if (mess.finish) {
        screenshot.screens.push({left: parseInt(mess.left), top: parseInt(screenshot.heightUl*screenshot.scrollStep), data: data});
        screenshot.screenShotParams = mess;
        console.log(mess);
        screenshot.createScreenShot();
      } else {       
        chrome.tabs.executeScript(screenshot.thisTabId, {code:'var result;window.scrollBy(0, window.innerHeight);'});
          screenshot.screens.push({left: parseInt(mess.left), top: parseInt(screenshot.heightUl*screenshot.scrollStep), data: data});
          screenshot.scrollStep++;
        screenshot.addScreen({
          start: false
        });
      }
    };
    var timeoutInterval = localStorage.speed;
    setTimeout(function () {
      chrome.windows.update(screenshot.thisWindowId, {focused: true}, function () {
        chrome.tabs.update(screenshot.thisTabId, {active: true}, function () {
          if (chrome.runtime.lastError) {
            console.error(chrome.runtime.lastError);
          }
          chrome.tabs.captureVisibleTab(null, {
            format: 'png'
          }, cb);
        })
      })
    }, timeoutInterval);
  }```

**Comment by freddy-daniel** [comment]
Your  fix is Not working now..

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
