### ISSUE TITLE
All page screenshot cropping image at height of viewport

### ISSUE THREAD

**Issue by madgoose** [Aminadav/screenshot-extension#113]
I'm quite certain this browser extension worked correctly when I first installed it. 

Currently, the `all page screenshot` option only captures the content visible in the viewport. 

The new document is the correct height to receive the rest of the content, but you just see the alpha transparency squares…

Chrome:
Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
