### ISSUE TITLE
Won't take picture of entire page, only what you see

### ISSUE THREAD

**Issue by katandmouse** [Aminadav/screenshot-extension#120]
In chrome on a Mac, it only takes a picture of what you see. It used to work. Perhaps an update broke it. It's been broken for some time now.

**Comment by spaulaus** [comment]
I can confirm that this is broken on Windows 10 Pro Version 1709 OS Build 16299.19, using Google Chrome Version 62.0.3202.75 (Official Build) (64-bit) and Open Screenshot Version 24.0

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.

**Comment by spaulaus** [comment]
Confirmed as resolved on 
OS Name:	Microsoft Windows 10 Pro
Version:	10.0.16299 Build 16299
Chrome : Version 64.0.3282.140 (Official Build) (64-bit)
Open Screenshot : V 29.0.0
