### ISSUE TITLE
Whole page function not working

### ISSUE THREAD

**Issue by gelfling83** [Aminadav/screenshot-extension#127]
When I try to do a "whole page screenshot" it's only capturing the visible screen -- it's not scrolling all the way to the bottom. 

I've been using the extension for a while now and this is a new bug -- it used to work just fine.

**Comment by freddy-daniel** [comment]
Yes full page screenshot not working. Its creating visible page image with full page document size.

**Comment by gelfling83** [comment]
Thank you for repeating my question back to me. What is the purpose of this
email?

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
