### ISSUE TITLE
whole page screenshot doesn't work properly

### ISSUE THREAD

**Issue by Yagitaaa** [Aminadav/screenshot-extension#128]
couple days before it worked OK, but suddenly when I try to use whole page screenshot it provides just visible screenshot with some panel for the rest. From time to time when I close a tab with a screenshot the whole Chrome is closed. I have Windows 10 64 bit and Chrome 64 bit. I did not change anything last 2 days. Today I reinstalled screenshot-extension, the same problem. Then I reinstalled Chrome itself, the same problem.
![- - 1](https://user-images.githubusercontent.com/26134228/33514015-38eff4f8-d701-11e7-87d5-a56a858ceabd.png)

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
