### ISSUE TITLE
Whole Page failure

### ISSUE THREAD

**Issue by thebrizzell** [Aminadav/screenshot-extension#131]
Tried to take a shot of http://www.krdo.com/news/colorado-springs/el-paso-county-commissioners-vote-to-ban-car-camping-on-county-roads/673177230 as a whole and it would only take visible screen

**Comment by yangziwen** [comment]
I meet the same problem, and the version of my chrome is 63.0.3239.132

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
