### ISSUE TITLE
Auto-transition to your Homepage every single time!

### ISSUE THREAD

**Issue by saurabhdua82** [Aminadav/screenshot-extension#134]
Hello!

I have a habit of instinctively clearing the entire "browsing history" of any web-browser before making it closed for the  day.

Next day access is consistently taking me to :: 
https://www.openscreenshot.com/

Therefore, should I stop clearing the browsing history altogether OR some tweaks can be accomplished at your level to prevent such a thing from occuring in the near future?

Please suggest?

**Comment by Aminadav** [comment]
Sorry for that, is it still happened to you?
