### ISSUE TITLE
no workee...

### ISSUE THREAD

**Issue by 808pants** [Aminadav/screenshot-extension#138]
well...the ONLY reason I got this extension was to capture a whole page, but for some reason, "whole page screenshot" does exactly what I do NOT need.  It apparently only captures the visible area, and leaves the rest as a gray/white checkerboard.

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.

**Comment by 808pants** [comment]
Thanks - I'll give it a go.

Dave
