### ISSUE TITLE
All page screen shot - PNG filesize lis limited - maxing at ~9250KB

### ISSUE THREAD

**Issue by kevinmorrisone** [Aminadav/screenshot-extension#24]
Hi...most amazing plugin...I dont know jQuery yet so I can't review code to fix. Problem: lots of screens reaches endpoint at 9250KB..local save file OK.  If you have more screens past this point then have to capture each screen and save manually.  Please comment and fix, if I can hep in any way please let me know!

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
