### ISSUE TITLE
Capture Region of Screen-function not working

### ISSUE THREAD

**Issue by zmillett** [Aminadav/screenshot-extension#38]
When I click this, nothing happens. I can capture the entire screen, but I specifically chose this app so I could select the area prior to capturing.

**Comment by daraloca** [comment]
I am having the same problem. Capture Region of the Screen function is the only link that can't be clicked. To me, it is the most important feature of the app. Please help.

**Comment by havana7** [comment]
I am having the same problem

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
