### ISSUE TITLE
Full Screenshot processes the page vertically, but not horizontal scroll.

### ISSUE THREAD

**Issue by soundornoise** [Aminadav/screenshot-extension#39]
Some pages layout their content horizontally instead of/as well as vertically. (e.g. Trello) The tool currently only checks for vertical scroll, but not horizontal.

**Comment by AminaG** [comment]
Would you like to try fixing it?

**Comment by soundornoise** [comment]
😄  I could be talked into it. However, saying as I'm not familiar with the internals, chrome extensions or screen capture, a point in the right direction would be appreciated.

Which file(s) am I most likely to need to change?
How do I test this? A link to the correct dev pages or a good blog would be help.

**Comment by Aminadav** [comment]
1JAPW5i4pedtYcJBV11DTvkqeQLB1zdg9s

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
