### ISSUE TITLE
Can not see the addition of URL / Impossible de voir l'ajout d'une URL

### ISSUE THREAD

**Issue by meb7** [Aminadav/screenshot-extension#41]
## In english

Hello,
I love your extension "Open Screenshot".
But there is a visibility problem in adding a URL (and date) in the header or footer of a screenshot.

**The part of the URL** (or date) **entry  was set on a transparent background**. 
**Most images readers have a BLACK background, and the URL text is BLACK too.**
**So the URL and the date are not visible on the screenshots.**.

Could you replace the glass bottom of the text in the header and footer by GREY background (some readers is a white background).
Thank you for your understanding to change the text background.

meb7
# 
## In french

Bonjour, 
J'aime beaucoup votre extension "Open Screenshot".
Mais il y a un problème de visibilité dans l'ajout d'une URL (et date) dans l'entête ou le pied de page d'une capture écran.

La partie de la saisie d'URL (ou date)  se créé sur un  fond transparent. 
La plupart des lecteurs d'images ont un arrière plan NOIR, et le texte de l'URL est en NOIR aussi.
Donc l'URL et la date ne sont pas visibles sur les captures d'écran.

Pourriez-vous remplacer le fond transparent du texte en entête et pied de page par un fond GRIS (certains lecteurs ont un fond blanc).
Merci de votre compréhension pour changer ce fond de texte.

meb7

**Comment by dandv** [comment]
@meb7: in [7 years](https://wiki.dandascalescu.com/essays/pita-threshold) of GitHubbing, I've never seen a bilingual issue.

You might want to read [The Ugly American Programmer](https://blog.codinghorror.com/the-ugly-american-programmer/) by the developer who started StackOverflow.

**Comment by Aminadav** [comment]
I have removed the headers & footers, so the issue will not be any more.
