### ISSUE TITLE
Viewer for screenshots shared online zooms to bottom of image by default

### ISSUE THREAD

**Issue by AustonZ** [Aminadav/screenshot-extension#58]
1.  Maximize your Chrome window
2.  Take a "visible screenshot" using the Chrome extension
3.  Click the "Share" button
4.  Wait for image to upload and be displayed in a new tab

Result:
Only the bottom of the screenshot is initially visible.  Example: http://www.openscreenshot.com/rkTFAkldg

Screenshot of example result (for screen resolution 2560x1440):
![image](https://cloud.githubusercontent.com/assets/13610250/22531436/9b93a100-e895-11e6-9857-7ebbbb95ab10.png)

Problem:
The box in which the image gets displayed has a fixed height, but the image is initially scaled to 100% and panned all the way to the bottom.

Suggestion:
Scale the image to fit by default.  Also, don't give the screenshot viewer a fixed height, if you can avoid it.

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
