### ISSUE TITLE
Capture region of the screen is not working

### ISSUE THREAD

**Issue by HwangTW** [Aminadav/screenshot-extension#59]
as tittle.

**Comment by Austenite2** [comment]
Also having this bug.  Chrome on Windows 10, multiple PCs.

This PC:
Chrome 56.0.2924.87 (Official Build) (32-bit)
Windows 10 Pro Version 1607 Build 14393.693 64 bit

**Comment by tulek7** [comment]
same here. win10. Chrome version 55.0.2883.87 (64-bit)

**Comment by pleabargain** [comment]
same: screen area not capturing
Google Chrome	56.0.2924.87 (Official Build) (64-bit)
OS	Linux 
JavaScript	V8 5.6.326.50

**Comment by jrholmes2017** [comment]
Also having this same problem with screen not capturing.  It does nothing as if total code link is broken when attempting to click that menu item.  
Google Chrom Version 58.0.3029.110 (64-bit)
OS X Yosemite Version 10.10.5

**Comment by claudeberube** [comment]
You need to update permissions in manifest.json.

 "permissions": [
        "<all_urls>",
        "tabs",
        "activeTab",
        "clipboardWrite"
    ],

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.

**Comment by Austenite2** [comment]
Thanks for your efforts!  Still not working for me  :(

Openscreenshot 29.0.0
Chrome 63.0.3239.132 (Official Build) (64-bit) (cohort: Stable)
Windows 10 64 bit 16299.192
