### ISSUE TITLE
截取整个网页功能有问题

### ISSUE THREAD

**Issue by wangmingsheng** [Aminadav/screenshot-extension#61]
截取整个网页的功能不稳，时常截取到的不是整个网页

**Comment by clemens-tolboom** [comment]
> 截取整个网页功能有问题

Interception of the entire page has a problem

> 截取整个网页的功能不稳，时常截取到的不是整个网页

Interception of the entire page of the function of instability, often intercepted to the whole page

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
