### ISSUE TITLE
website: typo is main header: "OpenScreensoot"

### ISSUE THREAD

**Issue by sgnl** [Aminadav/screenshot-extension#62]
🐛 Header says `OpenScreensoot`
 ✅  should be: `OpenScreenshot`

**Comment by philCryoport** [comment]
[https---www.openscreenshot.com--t=thankyou.pdf](https://github.com/Aminadav/screenshot-extension/files/1215441/https---www.openscreenshot.com--t.thankyou.pdf)

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
