### ISSUE TITLE
webpage icon is missing

### ISSUE THREAD

**Issue by pleabargain** [Aminadav/screenshot-extension#65]
my screengrab
http://www.openscreenshot.com/Hyqz1K-qg

this link is dead
https://raw.githubusercontent.com/AminaG/OpenScreenshot/master/src/images/icon256.png

**Comment by RohanTalip** [comment]
This is still the case.  Also, there is a spelling mistake of OpenScreens**oo**t (note the double 'o').

See also issue #64

**Comment by Aminadav** [comment]
Fixed.
