### ISSUE TITLE
'Capture region of the screen'

### ISSUE THREAD

**Issue by pitdoug1998** [Aminadav/screenshot-extension#68]
If memory serves this awesome feature worked before the most recent Chrome update?

**Comment by jlyon** [comment]
I can verify that this feature is not working in:
Chrome Version 58.0.3029.110 (64-bit)
OS: Mac OS Sierra 10.12.6 Beta (16G8c)

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
