### ISSUE TITLE
Screenshot of PDF file opened in Chrome

### ISSUE THREAD

**Issue by cecell** [Aminadav/screenshot-extension#69]
I opened a PDF file in Chrome and then when I clicked on the extension icon it shows me a request "Go to chrome://extensions, and check the box "Allow access to file URLs"":

![untitled](https://cloud.githubusercontent.com/assets/1248121/23915294/a4558e16-08b6-11e7-8089-db6c882e07c0.png)

When I go to the extensions page as it says to I do not see that option:

![untitled1](https://cloud.githubusercontent.com/assets/1248121/23915425/08ef6446-08b7-11e7-8637-69bed7bf102e.png)

Help!

**Comment by Aminadav** [comment]
We will look into that
