### ISSUE TITLE
"Capture region of the screen" not working

### ISSUE THREAD

**Issue by lucvw1975** [Aminadav/screenshot-extension#72]
Hi, I'm using Open Screenshot v24.0. I'm unable to Capture a region of the screen. When I press that button nothing happens. Workaround: take a screenshot of the whole or visible page and crop it with the tools that are available.

So, although I can work around this issue, it would be more practical to be able to use the "Capture region of the screen" functionality...

I hope you can tell me whether the problem is on my side or if it's a (known) bug ?

Thanks !

PS: I can see that more people have the same problem... I'm on Windows 10, Chrome version 57.0.2987.110 (64-bit).

**Comment by Aminadav** [comment]
I'm working to fix it in the next versions
