### ISSUE TITLE
No longer Printing :-( 

### ISSUE THREAD

**Issue by TheRealJoycey** [Aminadav/screenshot-extension#77]
Previously created post querying if any updates had been done to break functionality in which you closed it immediately advising of no updates released. Several PC's all experiencing the same and no longer Prints the screenshot rendering the extension useless (unless you want to share digitally).  I assume Chrome has been updated that has broken the facility. Any help in restoring it would be greatly appreciated, as its the best extension I used daily for Chrome (in my profession).  FYI...the "Print Preview" just shows a blank page and prints the same (i.e. nothing), although I can save the screenshot to an image file and jump through hoops to print it  (usually in a much smaller print quality than i want). Thanks Paul

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.
