### ISSUE TITLE
Prints Blank Pages

### ISSUE THREAD

**Issue by JustGittie** [Aminadav/screenshot-extension#80]
The same happens when printing to paper or saving as PDF...blank page.
Clicking on the Share or Gmail buttons will expend lengthy time that leads to nothing happening.

<img width="1324" alt="screen shot 2017-05-04 at 12 42 51 pm" src="https://cloud.githubusercontent.com/assets/28400542/25714830/5693d5dc-30c7-11e7-913c-a9a9c6b77b2a.png">
<img width="1321" alt="screen shot 2017-05-04 at 12 43 21 pm" src="https://cloud.githubusercontent.com/assets/28400542/25714831/56987042-30c7-11e7-8fb1-20f998a90297.png">
<img width="964" alt="screen shot 2017-05-04 at 12 46 45 pm" src="https://cloud.githubusercontent.com/assets/28400542/25715134/63f4cd7a-30c8-11e7-8718-a5fb7673de21.png">
<img width="979" alt="screen shot 2017-05-04 at 12 50 16 pm" src="https://cloud.githubusercontent.com/assets/28400542/25715135/63f7070c-30c8-11e7-8b3f-89841918f6e0.png">

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
