### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by ahaynes10** [Aminadav/screenshot-extension#82]
Hello - I've been trying to use the screenshot shortcuts and they're not functioning for me. Alt+Z worked once for an all page screenshot but won't work again. I've refreshed the page and cleared the cache and cookies.

**Comment by sam2de** [comment]
Same here, Using latest chrome: Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
