### ISSUE TITLE
không thể chụp được toàn bộ trang web

### ISSUE THREAD

**Issue by Rito-Tran** [Aminadav/screenshot-extension#87]
hiện plugin không thể chụp được toàn bộ trang web mặc dù các chức năng khác vẫn sử dụng bình thường

**Comment by clemens-tolboom** [comment]
> không thể chụp được toàn bộ trang web
Can not capture the whole site

> hiện plugin không thể chụp được toàn bộ trang web mặc dù các chức năng khác vẫn sử dụng bình thường
Currently the plugin can not capture the entire web page, although other functions are still used normally

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
