### ISSUE TITLE
'Thank you' page showing up repeatedly!

### ISSUE THREAD

**Issue by saurabhdua82** [Aminadav/screenshot-extension#89]
Hello there!

After its successful installation the "Thank you" page is showing up consistently upon first browser-start of the day!

The following URL is turning up always upon launching the Browser.

https://www.openscreenshot.com/?t=thankyou

Please help suggest further in the relevant context?

Thank you.

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
