### ISSUE TITLE
capture region of the screen does not work

### ISSUE THREAD

**Issue by dodominique** [Aminadav/screenshot-extension#90]
Hello,
Good job but the capture of a region of the screen does not work (everything ok except that option).
Google Chrome Version 60.0.3112.90 (Build officiel) (64 bits) on Windows 10 Pro 64 bits

Ciao !
Dom from Belgium

**Comment by claudeberube** [comment]
See #59

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
