### ISSUE TITLE
web client

### ISSUE THREAD

**Issue by claudeberube** [Aminadav/screenshot-extension#91]
So far I am very  happy with the result. Was able to launch extensions from page. Nevertheless, I need to support mobile, Chrome on Ipad.  Was thinking about  turning the plugin into a web client in order to have the editor for each widget. 

Would that be a feasible  alternative?

![widget-screenshot-capture](https://user-images.githubusercontent.com/29046526/29215992-2f9b071e-7e7b-11e7-98b9-b41698c2db4e.png)

**Comment by claudeberube** [comment]
#88

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
