### ISSUE TITLE
All page screenshot doesn't work on app.intercom.io domain

### ISSUE THREAD

**Issue by b-chan** [Aminadav/screenshot-extension#99]
**All Page Screenshot** feature doesn't work on https://app.intercom.io -- instead it takes a **Visible Screenshot**

**Comment by Fight4freeTech** [comment]
Similar Google Chrome updated and wouldn't work unless I clicked allow something... Now there are some pages that I cant get to give a full screenshot mostly news webpages but also a biblical studies page... Pages ( all of the http://biblehub.com and all of the www.i24news.tv/en pages don't work. but also a couple of the other news print pages also wont fully print screen )

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.
